ndcfg_tau: 0
dilate_tau: 30
inflate_tau: 0
dilate_settings: ./assets/dilate_settings/sd1.5_1024x1024.txt
inflate_settings: ~
ndcfg_dilate_settings: ~
inflate_transform: ~
progressive: false
num_inference_steps: 50
inference_batch_size: 4
num_iters_per_prompt: 1
latent_height: 128
latent_width: 128
pixel_height: 1024
pixel_width: 1024