ndcfg_tau: 35
dilate_tau: 35
inflate_tau: 0
sdedit_tau: 0
dilate_settings: ./assets/dilate_settings/sdxl_4096x2048.txt
inflate_settings: ~
#ndcfg_dilate_settings: ./assets/ndcfg_dilate_settings/sdxl_4096x2048.txt
ndcfg_dilate_settings: ~
inflate_transform: ~
progressive: false
num_inference_steps: 50
inference_batch_size: 4
num_iters_per_prompt: 1
latent_height: 256
latent_width: 512
pixel_height: 2048
pixel_width: 4096
